In [11]:
import numpy as np

In [12]:
a = np.array([3, 1, 5])

In [13]:
a

array([3, 1, 5])

In [14]:
a.shape

(3,)

In [15]:
a = np.arange(15).reshape(3, 5)

In [16]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [17]:
a.shape

(3, 5)

In [18]:
a.dtype

dtype('int64')

In [19]:
a.size

15

In [21]:
n = 1
m = 2

p = n + m
p

3

In [23]:
a = [1, 2, 3]
b = [10, 20, 10]

c = a + b
c

[1, 2, 3, 10, 20, 10]

In [24]:
c = a - b
c

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [25]:
a1 = np.array([1, 2, 3])
b1 = np.array([10, 20, 30])

a1 + b1

array([11, 22, 33])

In [26]:
import pandas as pd

In [27]:
data = {'Animal': ['Dog',  'Orangutan', 'Eagle','Pandas', "Elephant"],
        'Name': ['Ellen',  'Adam',  'Joe', 'Eve','Eve'],
        'Legs': [4, 2, 1, 3,4],
        'IsNice': [1,0,0,0,1]}

df = pd.DataFrame(data, columns=['Animal', 'Name', 'Legs', 'IsNice'])

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
Animal    5 non-null object
Name      5 non-null object
Legs      5 non-null int64
IsNice    5 non-null int64
dtypes: int64(2), object(2)
memory usage: 240.0+ bytes


In [29]:
df

Animal   Name  Legs  IsNice
0        Dog  Ellen     4       1
1  Orangutan   Adam     2       0
2      Eagle    Joe     1       0
3     Pandas    Eve     3       0
4   Elephant    Eve     4       1

In [30]:
#normalisation

from pandas.io.json import json_normalize

In [31]:
dfx = [{'id': 1, 'name': {'first': 'Anna', 'last': 'Rich'}},
         {'name': {'given': 'Anna', 'family': 'Broke'}},
         {'id': 2, 'name': {'first': 'Anna', 'last': 'Here'}}]

In [32]:
dfx

[{'id': 1, 'name': {'first': 'Anna', 'last': 'Rich'}},
 {'name': {'given': 'Anna', 'family': 'Broke'}},
 {'id': 2, 'name': {'first': 'Anna', 'last': 'Here'}}]

In [33]:
json_normalize(dfx)

id name.family name.first name.given name.last
0  1.0         NaN       Anna        NaN      Rich
1  NaN       Broke        NaN       Anna       NaN
2  2.0         NaN       Anna        NaN      Here

In [34]:
df.shape

(5, 4)

In [35]:
df.columns

Index(['Animal', 'Name', 'Legs', 'IsNice'], dtype='object')

In [37]:
df.describe(include="all")

Animal Name     Legs    IsNice
count           5    5  5.00000  5.000000
unique          5    4      NaN       NaN
top     Orangutan  Eve      NaN       NaN
freq            1    2      NaN       NaN
mean          NaN  NaN  2.80000  0.400000
std           NaN  NaN  1.30384  0.547723
min           NaN  NaN  1.00000  0.000000
25%           NaN  NaN  2.00000  0.000000
50%           NaN  NaN  3.00000  0.000000
75%           NaN  NaN  4.00000  1.000000
max           NaN  NaN  4.00000  1.000000

In [38]:
sorted_legs = df.sort_values(by=['Legs'], ascending=False)
sorted_legs

Animal   Name  Legs  IsNice
0        Dog  Ellen     4       1
4   Elephant    Eve     4       1
3     Pandas    Eve     3       0
1  Orangutan   Adam     2       0
2      Eagle    Joe     1       0

In [39]:
df[1:]

Animal  Name  Legs  IsNice
1  Orangutan  Adam     2       0
2      Eagle   Joe     1       0
3     Pandas   Eve     3       0
4   Elephant   Eve     4       1

In [40]:
sorted_legs[1:]

Animal  Name  Legs  IsNice
4   Elephant   Eve     4       1
3     Pandas   Eve     3       0
1  Orangutan  Adam     2       0
2      Eagle   Joe     1       0

In [41]:
sorted_legs[:3]

Animal   Name  Legs  IsNice
0       Dog  Ellen     4       1
4  Elephant    Eve     4       1
3    Pandas    Eve     3       0

In [42]:
sorted_legs.iloc[[0], [0]]

Animal
0    Dog

In [43]:
df.loc[[0], ['Name']]

Name
0  Ellen

In [44]:
df[df['Legs'] > 2]

Animal   Name  Legs  IsNice
0       Dog  Ellen     4       1
3    Pandas    Eve     3       0
4  Elephant    Eve     4       1

In [45]:
df[(df['Legs'] > 2) & (df['Name'] == 'Eve')][['Animal', 'Legs']]

Animal  Legs
3    Pandas     3
4  Elephant     4

In [47]:
df1 = df[df['Legs'].isin([4,2])]
df1

Animal   Name  Legs  IsNice
0        Dog  Ellen     4       1
1  Orangutan   Adam     2       0
4   Elephant    Eve     4       1

In [48]:
df['Legs'].sum()

14

In [49]:
df['Flock'] = df['Legs']*12
df

Animal   Name  Legs  IsNice  Flock
0        Dog  Ellen     4       1     48
1  Orangutan   Adam     2       0     24
2      Eagle    Joe     1       0     12
3     Pandas    Eve     3       0     36
4   Elephant    Eve     4       1     48

In [50]:
color = ['red','blue','brown','blue','orange']
df['Color'] = pd.Series(color)
df

Animal   Name  Legs  IsNice  Flock   Color
0        Dog  Ellen     4       1     48     red
1  Orangutan   Adam     2       0     24    blue
2      Eagle    Joe     1       0     12   brown
3     Pandas    Eve     3       0     36    blue
4   Elephant    Eve     4       1     48  orange

In [51]:
df = df.drop(['Name'], axis=1)
df

Animal  Legs  IsNice  Flock   Color
0        Dog     4       1     48     red
1  Orangutan     2       0     24    blue
2      Eagle     1       0     12   brown
3     Pandas     3       0     36    blue
4   Elephant     4       1     48  orange

In [52]:
def yes_no_recode(value):
    recoded = np.where(value == 1, "Yes", "No")
    return recoded

In [55]:
df["isNiceRecoded"] = df["IsNice"].apply(yes_no_recode)
df

Animal  Legs  IsNice  Flock   Color is_nice_recoded isNiceRecoded
0        Dog     4       1     48     red             Yes           Yes
1  Orangutan     2       0     24    blue              No            No
2      Eagle     1       0     12   brown              No            No
3     Pandas     3       0     36    blue              No            No
4   Elephant     4       1     48  orange             Yes           Yes

In [56]:
df = df.drop(['is_nice_recoded'], axis=1)
df

Animal  Legs  IsNice  Flock   Color isNiceRecoded
0        Dog     4       1     48     red           Yes
1  Orangutan     2       0     24    blue            No
2      Eagle     1       0     12   brown            No
3     Pandas     3       0     36    blue            No
4   Elephant     4       1     48  orange           Yes

In [57]:
df.to_csv('animals.csv')